<?php

/**
 * @file
 * Ding event calendar module.
 */

/**
 * Implements hook_menu().
 */
function ding_event_calendar_menu() {
  $items = array();

  $items['calendar/%/%'] = array(
    'title' => 'Calendar switch',
    'page callback' => 'ding_event_calendar_callback',
    'page arguments' => array(1, 2),
    'access callback' => array('user_access'),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['calendar/events/%'] = array(
    'title' => 'Print events',
    'page callback' => 'ding_event_calendar_events_callback',
    'page arguments' => array(2),
    'access callback' => array('user_access'),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * AJAX callback for rendering events calendar.
 */
function ding_event_calendar_callback($month, $year, $type = 'ajax') {
  if ($type == 'ajax') {
    $date = $year . '-' . str_pad($month, 2, '0', STR_PAD_LEFT);
    $output = _ding_event_calendar_content();
    $content = _ding_event_calendar_events($date);
    $commands = array();
    $commands[] = ajax_command_remove('#eventList');
    $commands[] = ajax_command_replace('#eventsCalendar', $output);
    $commands[] = ajax_command_replace('#eventList', $content);
    $page = array('#type' => 'ajax', '#commands' => $commands);
    ajax_deliver($page);
  }
  else {
    $output = t("Please enable Javascript!");
    return $output;
  }
}

/**
 * AJAX callback for rendering events list.
 */
function ding_event_calendar_events_callback($date, $type = 'ajax') {
  if ($type == 'ajax') {
    $output = _ding_event_calendar_events($date);
    $commands = array();
    $commands[] = ajax_command_changed('#eventList', '');
    $commands[] = ajax_command_replace('#eventList', $output);
    $page = array('#type' => 'ajax', '#commands' => $commands);
    ajax_deliver($page);
  }
  else {
    $output = t("Please enable Javascript in your browser.");
    return $output;
  }
}

/**
 * Implements hook_block_info().
 */
function ding_event_calendar_block_info() {
  $blocks['ding-event-calendar'] = array(
    'info' => t('Event Calendar'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function ding_event_calendar_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'ding-event-calendar':
      $block['subject'] = t('Event Calendar');
      $block['content'] = array(
        '#markup' => _ding_event_calendar_content(),
        '#attached' => array(
          'css' => array(drupal_get_path('module', 'ding_event_calendar') . '/css/ding_event_calendar.css'),
          'js' => array(drupal_get_path('module', 'ding_event_calendar') . '/js/ding_event_calendar.js'),
        ),
      );
      break;
  }
  return $block;
}

/**
 * Returns event calendar block content.
 */
function _ding_event_calendar_content() {
  $month = (int) (arg(1) ? arg(1) : date('m'));
  $year = (int) (arg(2) ? arg(2) : date('Y'));

  return '<div id="eventsCalendar">' . draw_controls() . draw_calendar($month, $year) . '</div><div id="eventList">' . get_events(date('Y-m-d')) . '</div>';
}

/**
 * Returning events list fro given date.
 */
function _ding_event_calendar_events($date) {
  if ((int) arg(1) && (int) arg(2)) {
    $date = ($date ? $date : date('Y-m'));
  }
  else {
    $date = (arg(2) ? arg(2) : date('Y-m-d'));
  }
  return '<div id="eventList">' . get_events($date) . '</div>';
}

/**
 * Rendering calendar navigation.
 */
function draw_controls() {
  global $language;

  $month = (int) (arg(1) ? arg(1) : date('m'));
  if (!$month) {
    $month = date('m');
  }
  $year = (int) (arg(2) ? arg(2) : date('Y'));

  $rendered_month = format_date(strtotime(date("01-$month-$year")), 'custom', 'F', NULL, $language->language);

  drupal_add_library('system', 'drupal.ajax');
  /* "next month" control */
  $next_month_link = l(
    t('>>>'),
    'calendar/' . ($month != 12 ? $month + 1 : 1) . '/' . ($month != 12 ? $year : $year + 1) . '/nojs',
    array('attributes' => array('class' => 'use-ajax control slick-arrow slick-next'))
  );

  /* "previous month" control */
  $previous_month_link = l(
    t('<<<'),
    'calendar/' . ($month != 1 ? $month - 1 : 12) . '/' . ($month != 1 ? $year : $year - 1) . '/nojs',
    array('attributes' => array('class' => 'use-ajax control slick-arrow slick-prev '))
  );

  /* bringing the controls together */
  $controls = '<div class="navi-heading slick-slider">' . $previous_month_link . '<h2>' . $rendered_month . '</h2>' . $next_month_link . ' </div>';

  return $controls;
}

/**
 * Rendering calendar.
 */
function draw_calendar($month, $year) {
  /* draw table */
  $calendar = '<table cellpadding="0" cellspacing="0" id="calendar">';

  /* table headings */
  $headings = array(
    t('Mon'),
    t('Tue'),
    t('Wed'),
    t('Thu'),
    t('Fri'),
    t('Sat'),
    t('Sun'),
  );
  $calendar .= '<tr class="calendar-row"><td class="calendar-day-head">' . implode('</td><td class="calendar-day-head">', $headings) . '</td></tr>';

  /* days and weeks vars now ... */
  $running_day = date('w', mktime(0, 0, 0, $month, 0, $year));
  $days_in_month = date('t', mktime(0, 0, 0, $month, 1, $year));
  $days_in_this_week = 1;
  $day_counter = 0;
  $classes = [];

  /* row for week one */
  $calendar .= '<tr class="calendar-row">';

  /* print "blank" days until the first of the current week */
  for ($x = 0; $x < $running_day; $x++) {
    $calendar .= '<td class="calendar-day-np"> </td>';
    $days_in_this_week++;
  }

  /* keep going with days.... */
  for ($list_day = 1; $list_day <= $days_in_month; $list_day++) {
    $form_date = $year . '-' . sprintf("%02s", $month) . '-' . sprintf("%02s", $list_day);

    /* add in the day number */
    $query = db_select('node', 'n')
      ->fields('n', array('nid'))
      ->condition('n.type', 'ding_event')
      ->condition('n.status', 1);
    $query->addJoin('INNER', 'field_data_field_ding_event_date', 'ed', 'n.nid=ed.entity_id');
    $query->addField('ed', 'field_ding_event_date_value');
    $query->addField('ed', 'field_ding_event_date_value2');
    $query->where("DATE_FORMAT(CONVERT_TZ(field_ding_event_date_value, '+00:00', :timezone), '%Y-%m-%d') <= :date", array(':timezone' => date('P'), ':date' => $form_date));
    $query->where("DATE_FORMAT(CONVERT_TZ(field_ding_event_date_value2, '+00:00', :timezone), '%Y-%m-%d') >= :date", array(':timezone' => date('P'), ':date' => $form_date));

    if (module_exists('domain')) {
      $domain = domain_get_domain();
      if (!empty(variable_get('culture_frontend_enable_ding_event_calendar_domain_' . $domain['domain_id'], FALSE))) {
        $query->addJoin(
          'INNER',
          'domain_access',
          'da',
          "n.nid=da.nid AND ((da.realm = 'domain_id' AND da.gid=:domain_id) OR (da.realm = 'domain_site' AND da.gid = :domain_id))",
          array(
            ':domain_id' => $domain['domain_id'],
          )
        );
      }
    }
    $classes[$form_date][] = 'calendar-day';

    if ($query) {
      $events = $query->execute()->fetchAll();
      $event_day = $query->execute()->rowCount();
    }

    if (!empty($events)) {
      foreach ($events as $event) {
        $begin = new DateTime($event->field_ding_event_date_value);
        $end = new DateTime($event->field_ding_event_date_value2);
        if ($begin->diff($end)->d > 0) {
          $classes[$begin->format('Y-m-d')][] = 'event-start';
          $classes[$end->format('Y-m-d')][] = 'event-end';

          $interval = DateInterval::createFromDateString('1 day');
          $period = new DatePeriod($begin->modify('+1 day'), $interval, $end);
          foreach ($period as $item) {
            $classes[$item->format('Y-m-d')][] = 'event-progress';
          }
        }
      }
    }
    if (empty($event_day)) {
      $list_day_printed = $list_day;
    }
    else {
      $list_day_printed = l($list_day, '/calendar/events/' . $form_date, array('attributes' => array('class' => 'use-ajax')));
    }

    if ($form_date == date('Y-m-d')) {
      $classes[$form_date][] = 'current-day';
    }

    if (!empty($event_day)) {
      $classes[$form_date][] = 'has-events';
    }

    $classes_str = implode(' ',array_unique($classes[$form_date]));
    $calendar .= "<td class='{$classes_str}'>";

    $calendar .= '<div class="day-number">' . $list_day_printed . '</div>';

    $calendar .= '</td>';
    if ($running_day == 6) {
      $calendar .= '</tr>';
      if (($day_counter + 1) != $days_in_month) {
        $calendar .= '<tr class="calendar-row">';
      }
      $running_day = -1;
      $days_in_this_week = 0;
    }
    $days_in_this_week++;
    $running_day++;
    $day_counter++;
  }

  /* finish the rest of the days in the week */
  if ($days_in_this_week < 8) {
    for ($x = 1; $x <= (8 - $days_in_this_week); $x++) {
      $calendar .= '<td class="calendar-day-np"> </td>';
    }
  }

  /* final row */
  $calendar .= '</tr>';

  /* end the table */
  $calendar .= '</table>';

  /* all done, return result */
  return $calendar;
}

/**
 * Fetching events list from database.
 *
 * @param string $date
 *   Curent calendar date.
 */
function get_events($date) {
  global $language;

  $limit = variable_get('ding_event_calendar_limit', '');

  $rendering_date = format_date(strtotime($date), 'ding_date_only', NULL, NULL, $language->language);
  $timezone = date('P');
  $results = array();

  $query = db_select('node', 'n')
    ->fields('n', array('nid'))
    ->condition('n.type', 'ding_event', '=')
    ->condition('n.status', 1, '=');
  $query->addJoin('INNER', 'field_data_field_ding_event_date', 'ed', 'n.nid=ed.entity_id');
  $query->where("DATE_FORMAT(CONVERT_TZ(field_ding_event_date_value, '+00:00', :timezone), '%Y-%m-%d') <= :date", array(':timezone' => $timezone, ':date' => $date));
  $query->where("DATE_FORMAT(CONVERT_TZ(field_ding_event_date_value2, '+00:00', :timezone), '%Y-%m-%d') >= :date", array(':timezone' => $timezone, ':date' => $date));
  $query->orderBy('ed.field_ding_event_date_value', 'asc');

  if (!empty($limit)) {
    $query->range(0, $limit);
  }

  if (module_exists('domain')) {
    $domain = domain_get_domain();
    if (!empty(variable_get('culture_frontend_enable_ding_event_calendar_domain_' . $domain['domain_id'], FALSE))) {
      $query->addJoin(
        'INNER',
        'domain_access',
        'da',
        "n.nid=da.nid AND ((da.realm = 'domain_id' AND da.gid=:domain_id) OR (da.realm = 'domain_site' AND da.gid = :domain_id))",
        array(
          ':domain_id' => $domain['domain_id'],
        )
      );
    }
  }
  if ($query) {
    $results = $query->execute()->fetchAll();
  }

  $items = array();
  foreach ($results as $item) {
    $node = node_load($item->nid);
    $items[$node->nid] = $node;
  }

  return theme('ding_events_list', array(
    'items' => $items,
    'date' => $rendering_date,
  ));
}

/**
 * Implements hook_theme().
 */
function ding_event_calendar_theme($existing, $type, $theme, $path) {
  return array(
    'ding_events_list' => array(
      'variables' => array('items' => NULL, 'date' => NULL),
      'path' => $path . '/templates',
      'template' => 'events-list',
    ),
  );
}

/**
 * Implements hook_form_alter().
 */
function ding_event_calendar_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'ctools_block_content_type_edit_form' && $form_state['pane']->subtype == 'ding_event_calendar-ding-event-calendar') {
    // Adding items limit field.
    $limit = variable_get('ding_event_calendar_limit', '');
    $form['limit'] = array(
      '#type' => 'textfield',
      '#title' => t('Limit'),
      '#description' => t('Limit amount of items in event list. If field value is "empty" or "0", all available items will be shown.'),
      '#size' => 10,
      '#weight' => '10',
      '#default_value' => !empty($limit) ? $limit : '',
    );

    // Custom submit callback.
    $form['#submit'][] = 'ding_event_calendar_settings_form_submit';
  }
}

/**
 * Calendar block settings form submit callback.
 */
function ding_event_calendar_settings_form_submit($form, &$form_state) {
  // Process items limit.
  variable_set('ding_event_calendar_limit', $form_state['values']['limit']);
}
